# Generated by Django 4.2 on 2024-09-26 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0008_product_is_published"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["name", "category", "created_at", "updated_at"],
                "permissions": [
                    ("set_published_status", "can change status is_published"),
                    ("can_edit_description", "can edit description"),
                    ("can_edit_category", "can edit category"),
                ],
                "verbose_name": "Товар",
                "verbose_name_plural": "Товары",
            },
        ),
    ]
